// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASNMZR0YKbVatHrZGZZPn6_bx6oXSDY1s',
    appId: '1:279338980315:web:2fdf62d40e8a61189ccdfe',
    messagingSenderId: '279338980315',
    projectId: 'studyhub-533bb',
    authDomain: 'studyhub-533bb.firebaseapp.com',
    storageBucket: 'studyhub-533bb.appspot.com',
    measurementId: 'G-P1XK92Y8S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY-fKDW7GD7qsDRXet6Jp7eGOmd4VsP_Y',
    appId: '1:279338980315:android:f9bdcecfb5919db59ccdfe',
    messagingSenderId: '279338980315',
    projectId: 'studyhub-533bb',
    storageBucket: 'studyhub-533bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLc_ydhSHgCAIyWQGVgIkYF_dhjGGmbag',
    appId: '1:279338980315:ios:669f3625f22778849ccdfe',
    messagingSenderId: '279338980315',
    projectId: 'studyhub-533bb',
    storageBucket: 'studyhub-533bb.appspot.com',
    iosBundleId: 'com.example.studyhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLc_ydhSHgCAIyWQGVgIkYF_dhjGGmbag',
    appId: '1:279338980315:ios:c62b61c825a669609ccdfe',
    messagingSenderId: '279338980315',
    projectId: 'studyhub-533bb',
    storageBucket: 'studyhub-533bb.appspot.com',
    iosBundleId: 'com.example.studyhub.RunnerTests',
  );
}
